import { describe, it, expect, vi } from 'vitest'
import { screen, fireEvent } from '@testing-library/react'
import { AssetCard } from '@/components/AssetCard'
import { createAssetWithUrl, createVideoAsset, createPdfAsset } from '../fixtures/assets'
import { renderWithRouter } from '../utils/render'

// Mock sonner for CopyButton
vi.mock('sonner', () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn(),
  },
}))

describe('AssetCard', () => {
  it('should render asset filename', () => {
    const asset = createAssetWithUrl({ filename: 'my-photo.png' })
    renderWithRouter(<AssetCard asset={asset} />)

    expect(screen.getByText('my-photo.png')).toBeInTheDocument()
  })

  it('should render asset size', () => {
    const asset = createAssetWithUrl({ size: 1024 * 100 }) // 100KB
    renderWithRouter(<AssetCard asset={asset} />)

    expect(screen.getByText('100 KB')).toBeInTheDocument()
  })

  it('should display thumbnail for image assets', () => {
    const asset = createAssetWithUrl({
      mimeType: 'image/png',
      altText: 'Test image',
    })
    renderWithRouter(<AssetCard asset={asset} />)

    const img = screen.getByRole('img')
    expect(img).toBeInTheDocument()
    // URL is generated by the fixture with CDN domain
    expect(img).toHaveAttribute('src', asset.url)
    expect(img).toHaveAttribute('alt', 'Test image')
  })

  it('should use filename as alt text when altText is not provided', () => {
    const asset = createAssetWithUrl({
      mimeType: 'image/png',
      filename: 'test-image.png',
      altText: null,
    })
    renderWithRouter(<AssetCard asset={asset} />)

    const img = screen.getByRole('img')
    expect(img).toHaveAttribute('alt', 'test-image.png')
  })

  it('should display icon for video assets', () => {
    const asset = {
      ...createVideoAsset(),
      url: 'https://cdn.test/video.mp4',
    }
    renderWithRouter(<AssetCard asset={asset} />)

    // Should not have an img element
    expect(screen.queryByRole('img')).not.toBeInTheDocument()
  })

  it('should display icon for PDF assets', () => {
    const asset = {
      ...createPdfAsset(),
      url: 'https://cdn.test/doc.pdf',
    }
    renderWithRouter(<AssetCard asset={asset} />)

    // Should not have an img element
    expect(screen.queryByRole('img')).not.toBeInTheDocument()
  })

  it('should show checkbox in selection mode', () => {
    const asset = createAssetWithUrl()
    renderWithRouter(<AssetCard asset={asset} selectionMode={true} />)

    expect(screen.getByRole('checkbox')).toBeInTheDocument()
  })

  it('should show checkbox when selected', () => {
    const asset = createAssetWithUrl()
    renderWithRouter(<AssetCard asset={asset} selected={true} />)

    expect(screen.getByRole('checkbox')).toBeInTheDocument()
    expect(screen.getByRole('checkbox')).toBeChecked()
  })

  it('should not show checkbox when not in selection mode and not selected', () => {
    const asset = createAssetWithUrl()
    renderWithRouter(<AssetCard asset={asset} selectionMode={false} selected={false} />)

    expect(screen.queryByRole('checkbox')).not.toBeInTheDocument()
  })

  it('should call onSelect when checkbox is toggled', () => {
    const asset = createAssetWithUrl()
    const handleSelect = vi.fn()

    renderWithRouter(
      <AssetCard
        asset={asset}
        selectionMode={true}
        onSelect={handleSelect}
      />
    )

    fireEvent.click(screen.getByRole('checkbox'))
    expect(handleSelect).toHaveBeenCalledWith(asset.id, true)
  })

  it('should have ring style when selected', () => {
    const asset = createAssetWithUrl()
    renderWithRouter(<AssetCard asset={asset} selected={true} />)

    const card = screen.getByText(asset.filename).closest('.group')
    expect(card).toHaveClass('ring-2')
    expect(card).toHaveClass('ring-primary')
  })

  it('should render links to asset detail page', () => {
    const asset = createAssetWithUrl({ id: 'test-asset-id' })
    renderWithRouter(<AssetCard asset={asset} />)

    const links = screen.getAllByRole('link')
    expect(links.length).toBeGreaterThan(0)
  })

  it('should have lazy loading on images', () => {
    const asset = createAssetWithUrl({ mimeType: 'image/jpeg' })
    renderWithRouter(<AssetCard asset={asset} />)

    const img = screen.getByRole('img')
    expect(img).toHaveAttribute('loading', 'lazy')
  })
})
